version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.1
  clojure: lambdaisland/clojure@0.0.2

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - run: npm install ws
            - kaocha/execute:
                args: "clj --reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
            - kaocha/execute:
                args: "cljs --reporter documentation"
                clojure_version: << parameters.clojure_version >>
            - kaocha/upload_codecov:
                flags: clj

jobs:
  java-15-clojure-1_10:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.10.1"}}]

  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.1"}}]

  java-9-clojure-1_10:
    executor: clojure/openjdk9
    steps: [{checkout_and_run: {clojure_version: "1.10.1"}}]

  java-8-clojure-1_10:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.10.1"}}]

  babashka-tests:
    executor: clojure/openjdk8
    steps:
      - checkout
      - run:
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          sudo ./install
          bb test:bb

workflows:
  kaocha_test:
    jobs:
      - java-15-clojure-1_10
      - java-11-clojure-1_10
      - java-9-clojure-1_10
      - java-8-clojure-1_10
      - babashka-tests
